### ISSUE TITLE
Megaface datasets

### ISSUE THREAD

**Issue by Carinazhao22** [haibo-qiu/FROM#2]
Hello,

Thanks for sharing the codes. I want to test on Megaface datasets. How I can access to this datasets? In the official website announcement, Megaface data are no longer being distributed. Thanks!

**Comment by wangfei54** [comment]
you can see https://github.com/deepinsight/insightface/tree/master/recognition/_evaluation_/megaface

**Comment by wangfei54** [comment]
> Hello,
> 
> Thanks for sharing the codes. I want to test on Megaface datasets. How I can access to this datasets? In the official website announcement, Megaface data are no longer being distributed. Thanks!

Have you run through all the code before the training? In the data preparation stage, I can't run the second step of the data preparation stage. Without webface dataset, how do you solve it

eg：WebFace_LMDB = 'data/datasets/faces_webface_112x112/temp/train.lmdb'
       WebFace_Images = 'data/datasets/faces_webface_112x112/images/'
       WebFace_List = 'data/datasets/faces_webface_112x112/images.txt'

**Comment by Carinazhao22** [comment]
i haven't run all the codes. i just used the provided lmdb.

**Comment by haibo-qiu** [comment]
Hi there~

Sorry for my late reply. @wangfei54 We actually did not provide the original image data of WebFace, you may access this dataset through [insightface](https://github.com/deepinsight/insightface) or [face.evoLVe](https://github.com/ZhaoJ9014/face.evoLVe). Once you get the data, you can modify the path correspondingly. Note that `images.txt` is just the names of each image for fast iteration, you can just travel the entire data path to get these names. 

In addition, we use 112X96 size in our main experiments and 112X112 only for `O_LFW` in Sec.4.10 of our paper. 
I guess these left `data/datasets/faces_webface_112x112` path are from my last experiment for `O_LFW` .

**Comment by Carinazhao22** [comment]
Hi,

Thanks for the response! I'm wondering where i can get the .pkl file. The data loader in megaface_mp.py needs to load the .pkl file.

**Comment by haibo-qiu** [comment]
@Carinazhao22 
Hi, I am not so sure I can still find those pkl files, but you refer to this [file](https://github.com/haibo-qiu/FROM/blob/main/data/facescrub_pkl_info.py) (newly uploaded) for how to generate these files.

I will let you know if I find those pkl files later.
