### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by lustudy** [haibo-qiu/FROM#5]
![微信图片_20220929161750](https://user-images.githubusercontent.com/114651707/192978777-9487b862-3a72-4ec9-9a3a-36760fe59797.jpg)
Why the first training session started ACC has always been the same

**Comment by haibo-qiu** [comment]
Hi @lustudy,

I don't understand what you mean, please be more specific.

**Comment by JeethuSrini** [comment]
hi @lustudy 

Is this the same model provided?? I have got results with ACC 96%

**Comment by haibo-qiu** [comment]
Feel free to reopen this issue if you have any further questions.
