### ISSUE TITLE
preprocessing images

### ISSUE THREAD

**Issue by Carinazhao22** [haibo-qiu/FROM#6]
Hello,

I have preprocessed images to 112x112 using MTCNN. How can I convert them to 112x96 used in the papers? Is it correct way to do this? Thanks!

**Comment by haibo-qiu** [comment]
Hi @Carinazhao22,

The default way is to use the generated [CASIA-112x96-LMDB.lmdb](https://drive.google.com/drive/folders/12r0QEQFb8MOxh1ZtX679Pnx4g8hknLOg) we provided.
The 112x96 format images we used are originally from [CosFace](https://arxiv.org/abs/1801.09414), you may refer to these [preprocessing steps](https://github.com/wy1iu/sphereface#part-1-preprocessing).

Another possible solution is using [this file](https://github.com/haibo-qiu/SynFace/blob/main/data/imgs_crop/face_align_crop.py) for cropping. The usage is like this:
```
python -u face_align_crop.py -j 8 -source_root PATH_TO_DATA -dest_root PATH_TO_SAVE
```
I used this file to crop the synthetic face images with 256x256 to 112x96, and it also can take 112x112 as input. But I am not sure whether it works the same as CosFace preprocessing.

Generally, if applying the same cropping strategy for both training and testing data, the network is supposed to work.

**Comment by Carinazhao22** [comment]
Thanks. It works.

**Comment by haibo-qiu** [comment]
:thumbsup::thumbsup:
