### ISSUE TITLE
The pretrained model you provided is not available

### ISSUE THREAD

**Issue by amycao123** [haibo-qiu/FROM#7]
I downloaded the pretrained model from your given link, and successfully downloaded the package,but failed to unzip the package.It said that the file had broken down.So I would like to ask if it is possible for you to provide a new pretrained model?Much appreciate for your help.

**Comment by haibo-qiu** [comment]
Hi @amycao123,

Can you provide more information? like which pretrained model you used is broken and which source you used, google drive or baidu-yun

I re-download the pretrained weights `model_p4_baseline_9938_8205_3610.pth.tar` `model_p5_w1_9938_9470_6503.pth.tar` from this [google drive link](https://drive.google.com/drive/folders/12r0QEQFb8MOxh1ZtX679Pnx4g8hknLOg) and try to load them with pytorch as below:
![image](https://user-images.githubusercontent.com/31210561/220296609-0efea2fa-5f4a-4fff-b758-76ab7556af4c.png)
You can see I have successfully loaded them as parameter dicts and all keys can be accessible.

**Comment by amycao123** [comment]
Dear Mr.Qiu,
Thank you so much for your help.It turns out to be my mistake.I shouldn't have unziped that package.I tried to load the pretrained model the way you did and the successfully load it.
So the package is not broken down.It's my first time to run a deep learning code based on pytorch,and I hope you can understand the inconvenience brought to you.And I do appreciate your help.
Wish you good luck!


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Caozhixin
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2023.2.22




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haibo-qiu/FROM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haibo-qiu/FROM] The pretrained model you provided is not available (Issue #7)





 
Hi @amycao123,
 
Can you provide more information? like which pretrained model you used is broken and which source you used, google drive or baidu-yun
 
I re-download the pretrained weights model_p4_baseline_9938_8205_3610.pth.tar model_p5_w1_9938_9470_6503.pth.tar from this google drive link and try to load them with pytorch as below:
 
 You can see I have successfully loaded them as parameter dicts and all keys can be accessible.

**Comment by haibo-qiu** [comment]
Don't worry, everyone goes through a beginner stage. 
Good luck for your deep learning journey.

**Comment by amycao123** [comment]
Thank you so much!It's very kind of you to understand me and comfort me!
I do hope your scientific research goes well and enjoy your life!
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haibo-qiu/FROM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haibo-qiu/FROM] The pretrained model you provided is not available (Issue #7)





 
Don't worry, everyone goes through a beginner stage.
 Good luck for your deep learning journey.

**Comment by cotigoer** [comment]
你好@haibo-qiu,
我没有找到用于测试arcface和megaface的模型在你给出的链接中，请问这个是需要到官方网址去下载吗？
<img width="377" alt="1721725098806" src="https://github.com/user-attachments/assets/031660d2-7f71-458c-9fa7-7818c8c9d44c">
<img width="323" alt="1721725162599" src="https://github.com/user-attachments/assets/a3a1bbec-d5fe-48cc-8c0a-3401b6161446">
能拜托你向我提供相应模型的下载地址吗？我将十分感谢！！
