### ISSUE TITLE
AssertionError: torch not compiled with cuda enabled

### ISSUE THREAD

**Issue by shuxtonn** [haibo-qiu/FROM#8]
Running the following commands -
```
conda env create -f environment.yml
bash start.sh
```

It throws the following error-
AssertionError: torch not compiled with cuda enabled

**Comment by haibo-qiu** [comment]
It appears that Pytorch was installed without CUDA support.
This [link](https://stackoverflow.com/questions/57814535/assertionerror-torch-not-compiled-with-cuda-enabled-in-spite-upgrading-to-cud) may help.

**Comment by amycao123** [comment]
请问一下fpn.py中LResNet_Occ_2D类和LResNet_Occ_FC类这两个类在论文中有提到吗？想问一下为什么要写这两个类啊？不胜感激！

**Comment by haibo-qiu** [comment]
Hi @amycao123, 
Please refer to Table 7
![image](https://user-images.githubusercontent.com/31210561/233229993-eaa2df69-aa63-49ed-9ca3-cfb275532452.png)

**Comment by amycao123** [comment]
Thanks a lot! I am really sorry for missing this part.


曹至欣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haibo-qiu/FROM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haibo-qiu/FROM] AssertionError: torch not compiled with cuda enabled (Issue #8)





 
Hi @amycao123,
 Please refer to Table 7

**Comment by amycao123** [comment]
请问一下generate_lmdb.py文件中

其中这个faces_webface_112x112的文件在哪里啊？我看云盘里只有CASIA-112x96-LMDB.lmdb文件，应该如何获取上面faces_webface_112x112的文件呀

**Comment by haibo-qiu** [comment]
你可以从这个[链接](https://github.com/ZhaoJ9014/face.evoLVe#Data-Zoo)下载到不同size的数据

我们文章里面的主要实验都是用的112x96，至于这里用112x112是后续实验中为了测试其他数据集，具体细节详见我们文章的Sec.4.10

**Comment by amycao123** [comment]
好的谢谢


曹至欣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haibo-qiu/FROM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haibo-qiu/FROM] AssertionError: torch not compiled with cuda enabled (Issue #8)





 
你可以从这个链接下载到不同size的数据
 
我们文章里面的主要实验都是用的112x96，至于这里用112x112是后续实验中为了测试其他数据集，具体细节详见我们文章的Sec.4.10

**Comment by amycao123** [comment]
您好，想请问一下github中（见下图）

这个里面提供的预训练模型是文章中4.2节训练部分在WebFace dataset训练好的通用人脸识别模型吗？

**Comment by haibo-qiu** [comment]
Hi,
你这里的图好像没有上传成功
![image](https://github.com/haibo-qiu/FROM/assets/31210561/f152ab1f-1ab4-485a-a1d5-ca921e7bf622)

我们提供了两个训练好的模型，分别对应Table 5中 `Baseline` and `FROM`
![image](https://github.com/haibo-qiu/FROM/assets/31210561/5cc43d42-6076-41de-b7f3-1ab57809a0f8)

**Comment by amycao123** [comment]
好的好的 谢谢




曹至欣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haibo-qiu/FROM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haibo-qiu/FROM] AssertionError: torch not compiled with cuda enabled (Issue #8)





 
Hi,
 你这里的图好像没有上传成功
 
 
我们提供了两个训练好的模型，分别对应Table 5中 Baseline and FROM

**Comment by onlyadragon** [comment]
请问我运行过程中弹出：NotADirectoryError: [Errno 20] Not a directory: 'data/datasets/lfw-occ/pairs.txt'，这个文件可以在哪里找到？

**Comment by haibo-qiu** [comment]
Hi @onlyadragon,

这里的`pairs.txt`文件应该就是这个[Google Dirve](https://drive.google.com/drive/folders/12r0QEQFb8MOxh1ZtX679Pnx4g8hknLOg) 里面的`lfws.zip`所包含的`pairs.txt`。
